server:
  port: 8083
spring:
  datasource:
    url: jdbc:sqlserver://10.38.6.124:1433;databaseName=JG_Rummy_QA8;encrypt=true;trustServerCertificate=true
    username: jwrdbadmin
    password: Sc26uvhMMayX44VRAdGy
  data:
    mongodb:
      uri: mongodb://jwrmongouser:1xVaz1iKrodBdXcZ@10.38.6.23:27017/qa8_game_fee_by_variant?authSource=admin&readPreference=secondaryPreferred&ssl=false&retryWrites=true&maxIdleTimeMS=5000

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      bootstrap-servers: localhost:9092
      group-id: user-data-group-id
      max-poll-records: 500
      max-poll-interval-ms: 30000
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect